package com.yhh.csap.mt.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.yhh.csap.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserOps<M extends BaseUserOps<M>> extends CoreModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setSurgeryAt(java.util.Date surgeryAt) {
		set("surgeryAt", surgeryAt);
	}

	public java.util.Date getSurgeryAt() {
		return get("surgeryAt");
	}

	public void setSurgeryDuration(java.lang.String surgeryDuration) {
		set("surgeryDuration", surgeryDuration);
	}

	public java.lang.String getSurgeryDuration() {
		return getStr("surgeryDuration");
	}

	public void setMerNO(java.lang.String merNO) {
		set("merNO", merNO);
	}

	public java.lang.String getMerNO() {
		return getStr("merNO");
	}

	public void setHDays(java.lang.Integer hDays) {
		set("hDays", hDays);
	}

	public java.lang.Integer getHDays() {
		return getInt("hDays");
	}

	public void setHosp(java.lang.Integer hosp) {
		set("hosp", hosp);
	}

	public java.lang.Integer getHosp() {
		return getInt("hosp");
	}

	public void setFee(java.math.BigDecimal fee) {
		set("fee", fee);
	}

	public java.math.BigDecimal getFee() {
		return get("fee");
	}

	public void setTmEftId(java.lang.Integer tmEftId) {
		set("tmEftId", tmEftId);
	}

	public java.lang.Integer getTmEftId() {
		return getInt("tmEftId");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public void setCAt(java.util.Date cAt) {
		set("cAt", cAt);
	}

	public java.util.Date getCAt() {
		return get("cAt");
	}

	public void setDAt(java.util.Date dAt) {
		set("dAt", dAt);
	}

	public java.util.Date getDAt() {
		return get("dAt");
	}

	public void setMAt(java.util.Date mAt) {
		set("mAt", mAt);
	}

	public java.util.Date getMAt() {
		return get("mAt");
	}

	public void setDrExt(java.lang.String drExt) {
		set("dr_ext", drExt);
	}

	public java.lang.String getDrExt() {
		return getStr("dr_ext");
	}

	public void setHospExt(java.lang.String hospExt) {
		set("hosp_ext", hospExt);
	}

	public java.lang.String getHospExt() {
		return getStr("hosp_ext");
	}

    public void setIfPublic(java.lang.String ifPublic) {
        set("ifPublic", ifPublic);
    }

    public java.lang.String getIfPublic() {
        return getStr("ifPublic");
    }

}
