package com.yhh.csap.mt.base;

import com.jfinal.plugin.activerecord.IBean;
import com.yhh.csap.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserMedicalrecordsTax<M extends BaseUserMedicalrecordsTax<M>> extends CoreModel<M> implements IBean {

    public void setId(Integer id) {
        set("id", id);
    }

    public Integer getId() {
        return getInt("id");
    }

    public void setTaxId(Integer taxId) {
        set("taxId", taxId);
    }

    public Integer getTaxId() {
        return getInt("taxId");
    }

    public void setType(Integer type) {
        set("type", type);
    }

    public Integer getType() {
        return getInt("type");
    }

    public void setUmId(Integer umId) {
        set("umId", umId);
    }

    public Integer getUmId() {
        return getInt("umId");
    }

}
