package com.yhh.csap.mt.base;

import com.jfinal.plugin.activerecord.IBean;
import com.yhh.csap.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserMedicalrecords<M extends BaseUserMedicalrecords<M>> extends CoreModel<M> implements IBean {

    public void setId(java.lang.Integer id) {
        set("id", id);
    }

    public java.lang.Integer getId() {
        return getInt("id");
    }

    public void setTel(java.lang.String tel) {
        set("tel", tel);
    }

    public java.lang.String getTel() {
        return getStr("tel");
    }

    public void setIfCure(java.lang.String ifCure) {
        set("ifCure", ifCure);
    }

    public java.lang.String getIfCure() {
        return getStr("ifCure");
    }

    public void setDiseaseDesc(java.lang.String diseaseDesc) {
        set("diseaseDesc", diseaseDesc);
    }

    public java.lang.String getDiseaseDesc() {
        return getStr("diseaseDesc");
    }

    public void setTreatEffect(java.lang.Integer treatEffect) {
        set("treatEffect", treatEffect);
    }

    public java.lang.Integer getTreatEffect() {
        return getInt("treatEffect");
    }

    public void setIdCard(java.lang.String idCard) {
        set("idCard", idCard);
    }

    public java.lang.String getIdCard() {
        return getStr("idCard");
    }

    public void setCAt(java.util.Date cAt) {
        set("cAt", cAt);
    }

    public java.util.Date getCAt() {
        return get("cAt");
    }

    public void setDAt(java.util.Date dAt) {
        set("dAt", dAt);
    }

    public java.util.Date getDAt() {
        return get("dAt");
    }

    public void setMAt(java.util.Date mAt) {
        set("mAt", mAt);
    }

    public java.util.Date getMAt() {
        return get("mAt");
    }

    public void setIfPublic(java.lang.String ifPublic) {
        set("ifPublic", ifPublic);
    }

    public java.lang.String getIfPublic() {
        return getStr("ifPublic");
    }

    public void setUserId(java.lang.Integer userId) {
        set("userId", userId);
    }

    public java.lang.Integer getUserId() {
        return getInt("userId");
    }

    public void setName(java.lang.String name) {
        set("name", name);
    }

    public java.lang.String getName() {
        return getStr("name");
    }

    public void setSex(java.lang.String sex) {
        set("sex", sex);
    }

    public java.lang.String getSex() {
        return getStr("sex");
    }

    public void setAge(java.lang.Integer age) {
        set("age", age);
    }

    public java.lang.Integer getAge() {
        return getInt("age");
    }

    public void setSheng(java.lang.String sheng) {
        set("sheng", sheng);
    }

    public java.lang.String getSheng() {
        return getStr("sheng");
    }

    public void setShi(java.lang.String shi) {
        set("shi", shi);
    }

    public java.lang.String getShi() {
        return getStr("shi");
    }

    public void setQu(java.lang.String qu) {
        set("qu", qu);
    }

    public java.lang.String getQu() {
        return getStr("qu");
    }

    public void setAddress(java.lang.String address) {
        set("address", address);
    }

    public java.lang.String getAddress() {
        return getStr("address");
    }

    public void setAcne(java.lang.Integer acne) {
        set("acne", acne);
    }

    public java.lang.Integer getAcne() {
        return getInt("acne");
    }

    public void setTreatmentMhd(java.lang.Integer treatmentMhd) {
        set("treatmentMhd", treatmentMhd);
    }

    public java.lang.Integer getTreatmentMhd() {
        return getInt("treatmentMhd");
    }

    public void setEmail(java.lang.String email) {
        set("email", email);
    }

    public java.lang.String getEmail() {
        return getStr("email");
    }

    public void setWeixin(java.lang.String weixin) {
        set("weixin", weixin);
    }

    public java.lang.String getWeixin() {
        return getStr("weixin");
    }

}
