package com.yhh.csap.mt.base;

import com.jfinal.plugin.activerecord.IBean;
import com.yhh.csap.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDoctorTax<M extends BaseDoctorTax<M>> extends CoreModel<M> implements IBean {

    public void setId(Integer id) {
        set("id", id);
    }

    public Integer getId() {
        return getInt("id");
    }

    public void setDId(Integer dId) {
        set("dId", dId);
    }

    public Integer getDId() {
        return getInt("dId");
    }

    public void setTaxId(Integer taxId) {
        set("taxId", taxId);
    }

    public Integer getTaxId() {
        return getInt("taxId");
    }

    public void setType(Integer type) {
        set("type", type);
    }

    public Integer getType() {
        return getInt("type");
    }

}
