package com.yhh.csap.mt.base;

import com.jfinal.plugin.activerecord.IBean;
import com.yhh.csap.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDoctorVisit<M extends BaseDoctorVisit<M>> extends CoreModel<M> implements IBean {

    public void setId(Integer id) {
        set("id", id);
    }

    public Integer getId() {
        return getInt("id");
    }

    public void setDId(Integer dId) {
        set("dId", dId);
    }

    public Integer getDId() {
        return getInt("dId");
    }

    public void setNum(Integer num) {
        set("num", num);
    }

    public Integer getNum() {
        return getInt("num");
    }

    public void setAddress(String address) {
        set("address", address);
    }

    public String getAddress() {
        return getStr("address");
    }

    public void setVisitBAt(java.util.Date visitBAt) {
        set("visitBAt", visitBAt);
    }

    public java.util.Date getVisitBAt() {
        return get("visitBAt");
    }

    public void setVisitEAt(java.util.Date visitEAt) {
        set("visitEAt", visitEAt);
    }

    public java.util.Date getVisitEAt() {
        return get("visitEAt");
    }

    public void setVisitDate(java.util.Date visitDate) {
        set("visitDate", visitDate);
    }

    public java.util.Date getVisitDate() {
        return get("visitDate");
    }

    public void setStatus(Integer status) {
        set("status", status);
    }

    public Integer getStatus() {
        return getInt("status");
    }

    public void setDAt(java.util.Date dAt) {
        set("dAt", dAt);
    }

    public java.util.Date getDAt() {
        return get("dAt");
    }

    public void setCAt(java.util.Date cAt) {
        set("cAt", cAt);
    }

    public java.util.Date getCAt() {
        return get("cAt");
    }

    public void setMAt(java.util.Date mAt) {
        set("mAt", mAt);
    }

    public java.util.Date getMAt() {
        return get("mAt");
    }

    public void setOperId(java.util.Date operId) {
        set("operId", operId);
    }

    public java.util.Date getOperId() {
        return get("operId");
    }

}
