package com.yhh.csap.mt.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserOpsTax<M extends BaseUserOpsTax<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setUoId(Integer uoId) {
		set("uoId", uoId);
	}
	
	public Integer getUoId() {
		return getInt("uoId");
	}

	public void setTaxId(Integer taxId) {
		set("taxId", taxId);
	}
	
	public Integer getTaxId() {
		return getInt("taxId");
	}

	public void setType(Integer type) {
		set("type", type);
	}
	
	public Integer getType() {
		return getInt("type");
	}

}
