package com.yhh.csap.mt.base;

import com.jfinal.plugin.activerecord.IBean;
import com.yhh.csap.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserMedicalrecords<M extends BaseUserMedicalrecords<M>> extends CoreModel<M> implements IBean {

    public void setId(Integer id) {
        set("id", id);
    }

    public Integer getId() {
        return getInt("id");
    }

    public void setMrNo(String mrNo) {
        set("mrNo", mrNo);
    }

    public String getMrNo() {
        return getStr("mrNo");
    }

    public void setTel(String tel) {
        set("tel", tel);
    }

    public String getTel() {
        return getStr("tel");
    }

    public void setIfCure(Integer ifCure) {
        set("ifCure", ifCure);
    }

    public Integer getIfCure() {
        return getInt("ifCure");
    }

    public void setDiseaseDesc(String diseaseDesc) {
        set("diseaseDesc", diseaseDesc);
    }

    public String getDiseaseDesc() {
        return getStr("diseaseDesc");
    }

    public void setIdCard(String idCard) {
        set("idCard", idCard);
    }

    public String getIdCard() {
        return getStr("idCard");
    }

    public void setHosp(Integer hosp) {
        set("hosp", hosp);
    }

    public Integer getHosp() {
        return getInt("hosp");
    }

    public void setFee(String fee) {
        set("fee", fee);
    }

    public String getFee() {
        return getStr("fee");
    }

    public void setHDays(String hDays) {
        set("hDays", hDays);
    }

    public String getHDays() {
        return getStr("hDays");
    }

    public void setCAt(java.util.Date cAt) {
        set("cAt", cAt);
    }

    public java.util.Date getCAt() {
        return get("cAt");
    }

    public void setDAt(java.util.Date dAt) {
        set("dAt", dAt);
    }

    public java.util.Date getDAt() {
        return get("dAt");
    }

    public void setMAt(java.util.Date mAt) {
        set("mAt", mAt);
    }

    public java.util.Date getMAt() {
        return get("mAt");
    }

    public void setIfPublic(String ifPublic) {
        set("ifPublic", ifPublic);
    }

    public String getIfPublic() {
        return getStr("ifPublic");
    }

    public void setSurgeryAt(java.util.Date surgeryAt) {
        set("surgeryAt", surgeryAt);
    }

    public java.util.Date getSurgeryAt() {
        return get("surgeryAt");
    }

    public void setSurgeryDuration(String surgeryDuration) {
        set("surgeryDuration", surgeryDuration);
    }

    public String getSurgeryDuration() {
        return getStr("surgeryDuration");
    }

    public void setRemark(String remark) {
        set("remark", remark);
    }

    public String getRemark() {
        return getStr("remark");
    }

    public void setUserId(Integer userId) {
        set("userId", userId);
    }

    public Integer getUserId() {
        return getInt("userId");
    }

}
