package com.yhh.csap.mt.base;

import com.jfinal.plugin.activerecord.IBean;
import com.yhh.csap.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDoctorVisitApi<M extends BaseDoctorVisitApi<M>> extends CoreModel<M> implements IBean {

    public void setId(Integer id) {
        set("id", id);
    }

    public Integer getId() {
        return getInt("id");
    }

    public void setUrl(String url) {
        set("url", url);
    }

    public String getUrl() {
        return getStr("url");
    }

    public void setName(String name) {
        set("name", name);
    }

    public String getName() {
        return getStr("name");
    }

    public void setDvId(Integer dvId) {
        set("dvId", dvId);
    }

    public Integer getDvId() {
        return getInt("dvId");
    }

}
