package com.yhh.csap.mt.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserOpsDoctor<M extends BaseUserOpsDoctor<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setUoId(Integer uoId) {
		set("uoId", uoId);
	}
	
	public Integer getUoId() {
		return getInt("uoId");
	}

	public void setDId(Integer dId) {
		set("dId", dId);
	}
	
	public Integer getDId() {
		return getInt("dId");
	}

}
