package com.yhh.csap.mt;


import com.yhh.csap.mt.base.BaseDoctorVisitApi;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DoctorVisitApi extends BaseDoctorVisitApi<DoctorVisitApi> {
	public static final DoctorVisitApi dao = new DoctorVisitApi().dao();

	@Override
	public String getTableName() {
		return "mt_doctor_visit_api";
	}
}
