package com.yhh.csap.mt;


import com.jfinal.plugin.ehcache.CacheKit;
import com.yhh.csap.Consts;
import com.yhh.csap.admin.model.Taxonomy;
import com.yhh.csap.mt.base.BaseDoctorTax;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DoctorTax extends BaseDoctorTax<DoctorTax> {
	public static final DoctorTax dao = new DoctorTax().dao();

	@Override
	public String getTableName() {
		return "mt_doctor_tax";
	}

	public void delByDIdAndType(int dId,String type){
		List<DoctorTax> doctorTaxes=dao.find("select * from "+getTableName()+" where  dId=? and type=?",dId,type);
		for (DoctorTax doctorTax:doctorTaxes){
			doctorTax.delete();
		}
	}

	public void delByDId(int dId){
		List<DoctorTax> doctorTaxes=dao.find("select * from "+getTableName()+" where  dId=? ",dId);
		for (DoctorTax doctorTax:doctorTaxes){
			doctorTax.delete();
		}
	}

	public Taxonomy getTax(){
		return CacheKit.get(Consts.CACHE_NAMES.taxonomy.name(),getTaxId().toString());
	}


}
