package com.yhh.csap.mt;


import com.yhh.csap.mt.base.BaseDoctorVisit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DoctorVisit extends BaseDoctorVisit<DoctorVisit> {
	public static final DoctorVisit dao = new DoctorVisit().dao();

	@Override
	public String getTableName() {
		return "mt_doctor_visit";
	}
}
