package com.yhh.csap.mt;


import com.yhh.csap.Consts;
import com.yhh.csap.admin.model.Taxonomy;
import com.yhh.csap.mt.base.BaseDoctorInfo;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DoctorInfo extends BaseDoctorInfo<DoctorInfo> {
	public static final DoctorInfo dao = new DoctorInfo().dao();


	/**
	 * 擅长疾病分类
	 * @return
	 */
	public List<DoctorTax> getDT_A(){
		return DoctorTax.dao.findByCache(Consts.CACHE_NAMES.doctorTax.name(),"dt_a_".concat(getId().toString()),"select * from mt_doctor_tax where dId=? and type=1",getId());
	}
	/**
	 * 手术方式
	 * @return
	 */
	public List<DoctorTax> getDT_B(){
		return DoctorTax.dao.findByCache(Consts.CACHE_NAMES.doctorTax.name(),"dt_b_".concat(getId().toString()),"select * from mt_doctor_tax where dId=? and type=2",getId());
	}

	/**
	 * 职称
	 * @return
	 */
	public List<DoctorTax> getDT_C(){
		return DoctorTax.dao.findByCache(Consts.CACHE_NAMES.doctorTax.name(),"dt_c_".concat(getId().toString()),"select * from mt_doctor_tax where dId=? and type=3",getId());
	}



	@Override
	public String getTableName() {
		return "mt_doctor_info";
	}
}
