package com.yhh.csap.mt;


import com.yhh.csap.Consts;
import com.yhh.csap.mt.base.BaseDoctorVisit;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DoctorVisit extends BaseDoctorVisit<DoctorVisit> {
	public static final DoctorVisit dao = new DoctorVisit().dao();

	@Override
	public String getTableName() {
		return "mt_doctor_visit";
	}

	public DoctorInfo getDr(){
		DoctorInfo doctorInfo=DoctorInfo.dao.findFirstByCache(Consts.CACHE_NAMES.doctorInfo.name(),"id-"+getDId(),"select * from mt_doctor_info where id=? and dAt is null ",getDId());
		return doctorInfo;
	}

	public List<DoctorVisitApi> getVisitApi(){
		return DoctorVisitApi.dao.findByCache(Consts.CACHE_NAMES.doctorVisit.name(),"visitApi_"+getId(),"select * from mt_doctor_visit_api where dvId=?  ");
	}

}
