package com.yhh.csap.mt;


import com.yhh.csap.mt.base.BaseDoctorTax;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DoctorTax extends BaseDoctorTax<DoctorTax> {
	public static final DoctorTax dao = new DoctorTax().dao();

	@Override
	public String getTableName() {
		return "mt_doctor_tax";
	}
}
