package com.yhh.csap.mt;


import com.yhh.csap.mt.base.BaseReservationRecords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReservationRecords extends BaseReservationRecords<ReservationRecords> {
	public static final ReservationRecords dao = new ReservationRecords().dao();

	@Override
	public String getTableName() {
		return "mt_reservation_records";
	}
}
