package com.yhh.csap.mt;


import com.yhh.csap.Consts;
import com.yhh.csap.mt.base.BaseUserMedicalrecordsDoctor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserMedicalrecordsDoctor extends BaseUserMedicalrecordsDoctor<UserMedicalrecordsDoctor> {
	public static final UserMedicalrecordsDoctor dao = new UserMedicalrecordsDoctor().dao();

	@Override
	public String getTableName() {
		return "mt_user_medicalrecords_doctor";
	}

	public DoctorInfo getDr(){
		return DoctorInfo.dao.findFirstByCache(Consts.CACHE_NAMES.doctorInfo.name(),"id_"+getDId(),"select * from mt_doctor_info where id=? ",getDId());
	}
}
