package com.yhh.csap.mt;


import com.yhh.csap.Consts;
import com.yhh.csap.admin.model.Taxonomy;
import com.yhh.csap.mt.base.BaseUserMedicalrecords;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserMedicalrecords extends BaseUserMedicalrecords<UserMedicalrecords> {
	public static final UserMedicalrecords dao = new UserMedicalrecords().dao();

	public static enum TaxType{
		symptoms(6),deseases(5),opModes(2),bOpSymptoms(3),afOpSymptoms(4),treatEffect(1);

		private int val;

		private TaxType(int val){
			this.val=val;
		}

		public int getVal() {
			return val;
		}

		public void setVal(int val) {
			this.val = val;
		}
	}

	@Override
	public String getTableName() {
		return "mt_user_medicalrecords";
	}

	public List<UserMedicalrecordsTax> getTreatEffectTax(){
		return UserMedicalrecordsTax.dao.findByCache(Consts.CACHE_NAMES.userMedicalrecords.name(),"treatEffectTax_"+getId(),"select * from mt_user_medicalrecords_tax where umId=? and type='1'",getId());
	}

	public List<UserMedicalrecordsTax> getOpModelTax(){
		return UserMedicalrecordsTax.dao.findByCache(Consts.CACHE_NAMES.userMedicalrecords.name(),"opModelTax_"+getId(),"select * from mt_user_medicalrecords_tax where umId=? and type='2'",getId());
	}

	public List<UserMedicalrecordsTax> getBOpSymptomsTax(){
		return UserMedicalrecordsTax.dao.findByCache(Consts.CACHE_NAMES.userMedicalrecords.name(),"bOpSymptomsTax_"+getId(),"select * from mt_user_medicalrecords_tax where umId=? and type='3'",getId());
	}

	public List<UserMedicalrecordsTax> getAfOpSymptomsTax(){
		return UserMedicalrecordsTax.dao.findByCache(Consts.CACHE_NAMES.userMedicalrecords.name(),"afOpSymptomsTax_"+getId(),"select * from mt_user_medicalrecords_tax where umId=? and type='4'",getId());
	}
	public List<UserMedicalrecordsTax> getDiseasesTax(){
		return UserMedicalrecordsTax.dao.findByCache(Consts.CACHE_NAMES.userMedicalrecords.name(),"diseasesTax_"+getId(),"select * from mt_user_medicalrecords_tax where umId=? and type='5'",getId());
	}

	public List<UserMedicalrecordsTax> getSymptomsTax(){
		return UserMedicalrecordsTax.dao.findByCache(Consts.CACHE_NAMES.userMedicalrecords.name(),"symptomsTax_"+getId(),"select * from mt_user_medicalrecords_tax where umId=? and type='6'",getId());
	}


	public List<UserMedicalrecordsDoctor> getDrs(){
		return UserMedicalrecordsDoctor.dao.findByCache(Consts.CACHE_NAMES.userMedicalrecords.name(),"doctors_"+getId(),"select * from mt_user_medicalrecords_doctor where umId=?",getId() );
	}


}
