package com.yhh.csap.mt;


import com.yhh.csap.mt.base.BaseUserOpsTax;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserOpsTax extends BaseUserOpsTax<UserOpsTax> {
	public static final UserOpsTax dao = new UserOpsTax().dao();
}
