package com.yhh.csap.mt;


import com.yhh.csap.mt.base.BaseUserMedicalrecords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserMedicalrecords extends BaseUserMedicalrecords<UserMedicalrecords> {
	public static final UserMedicalrecords dao = new UserMedicalrecords().dao();

	@Override
	public String getTableName() {
		return "mt_user_medicalrecords";
	}
}
