package com.yhh.csap.mt;


import com.yhh.csap.mt.base.BaseUserMedicalrecordsTax;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserMedicalrecordsTax extends BaseUserMedicalrecordsTax<UserMedicalrecordsTax> {
	public static final UserMedicalrecordsTax dao = new UserMedicalrecordsTax().dao();

	@Override
	public String getTableName() {
		return "mt_user_medicalrecords_tax";
	}
}
