package com.yhh.csap.mt;


import com.yhh.csap.mt.base.BaseUserOpsDoctor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserOpsDoctor extends BaseUserOpsDoctor<UserOpsDoctor> {
	public static final UserOpsDoctor dao = new UserOpsDoctor().dao();
}
