package com.yhh.csap.mt;


import com.yhh.csap.mt.base.BaseUserMedicalrecordsDoctor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserMedicalrecordsDoctor extends BaseUserMedicalrecordsDoctor<UserMedicalrecordsDoctor> {
	public static final UserMedicalrecordsDoctor dao = new UserMedicalrecordsDoctor().dao();

	@Override
	public String getTableName() {
		return "mt_user_medicalrecords_doctor";
	}
}
