package com.yhh.csap.www.model;


import com.yhh.csap.www.model.base.BaseAtMe;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AtMe extends BaseAtMe<AtMe> {
	public static final AtMe dao = new AtMe().dao();

	public List<AtMe> findByUserId( int userId){
		return dao.find("select * from www_at_me where userId=? ",userId);
	}

	public void delByUserId(int userId){
		List<AtMe> list=findByUserId(userId);
		for (AtMe atMe:list){
			atMe.delete();
		}
	}


}
