package com.yhh.csap.www.model;


import com.yhh.csap.www.model.base.BaseAtMe;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AtMe extends BaseAtMe<AtMe> {
	public static final AtMe dao = new AtMe().dao();

	@Override
	public String getTableName() {
		return "www_at_me";
	}
}
