package com.yhh.csap.www.model;


import com.jfinal.plugin.ehcache.CacheKit;
import com.yhh.csap.Consts;
import com.yhh.csap.admin.model.Taxonomy;
import com.yhh.csap.admin.model.User;
import com.yhh.csap.www.model.base.BaseCarouselSetting;
import net.sf.ehcache.store.CacheKeySet;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CarouselSetting extends BaseCarouselSetting<CarouselSetting> {
	public static final CarouselSetting dao = new CarouselSetting().dao();

	@Override
	public String getTableName() {
		return "www_carousel_setting";
	}

	public String getAreaTxt(){
		List<Taxonomy> taxonomyList= CacheKit.get(Consts.CACHE_NAMES.taxonomy.name(),"carouselSettingAreasList");
		for(Taxonomy taxonomy:taxonomyList){
			if(taxonomy.getText().equals(getArea())){
				return taxonomy.getTitle();
			}
		}
		return Consts.BLANK;
	}

	public String getOperTxt(){
		User user=User.dao.findById(getOperId());
		return user==null?Consts.BLANK:user.getNickname();
	}

	public String getStatusTxt(){
		return getStatusTxt(getStatus());
	}



	public List findByArea(String area){
		return CarouselSetting.dao.find("select * from "+getTableName()+" where dAt is null and status='0' and area=?",area);
	}

}
