package com.yhh.csap.www.model;


import com.yhh.csap.www.model.base.BaseCarouselSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CarouselSetting extends BaseCarouselSetting<CarouselSetting> {
	public static final CarouselSetting dao = new CarouselSetting().dao();

	@Override
	public String getTableName() {
		return "www_carousel_setting";
	}
}
