package com.yhh.csap.www.model;


import com.yhh.csap.www.model.base.BaseFans;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Fans extends BaseFans<Fans> {
	public static final Fans dao = new Fans().dao();

	@Override
	public String getTableName() {
		return "www_fans";
	}
}
