package com.yhh.csap.www.model;


import com.yhh.csap.www.model.base.BaseLikeRecords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LikeRecords extends BaseLikeRecords<LikeRecords> {
	public static final LikeRecords dao = new LikeRecords().dao();

	@Override
	public String getTableName() {
		return "www_like_records";
	}
}
