package com.yhh.csap.www.model;


import cn.hutool.core.util.StrUtil;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.ehcache.CacheKit;
import com.yhh.csap.Consts;
import com.yhh.csap.admin.model.Taxonomy;
import com.yhh.csap.admin.model.User;
import com.yhh.csap.kits.DateKit;
import com.yhh.csap.www.model.base.BasePostInfo;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PostInfo extends BasePostInfo<PostInfo> {
	public static final PostInfo dao = new PostInfo().dao();

	@Override
	public String getTableName() {
		return "www_post_info";
	}

	public User getOper(){
		return User.dao.findFirstByCache(Consts.CACHE_NAMES.user.name(),"id_"+getOperId(),"select * from s_user where id=?",getOperId());
	}

	public User getChecker(){
		return User.dao.findFirstByCache(Consts.CACHE_NAMES.user.name(),"id_"+getCheckOperId(),"select * from s_user where id=?",getCheckOperId());
	}

	public Taxonomy getTax(){
		return CacheKit.get(Consts.CACHE_NAMES.taxonomy.name(),getTaxId().toString());
	}


	public String getCAtTxt(){
		return DateKit.dateToStr(getCAt(),DateKit.STR_DATEFORMATE);
	}

	public String getPostStatusTxt(){
		return getPostStatus().equals("0")?"已结":"未结";
	}

}
