package com.yhh.csap.www.model;


import com.yhh.csap.Consts;
import com.yhh.csap.admin.model.User;
import com.yhh.csap.www.model.base.BasePriLetter;

import java.math.BigInteger;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PriLetter extends BasePriLetter<PriLetter> {
	public static final PriLetter dao = new PriLetter().dao();

	@Override
	public String getTableName() {
		return "www_pri_letter";
	}


	public User getFromUser(){
		return User.dao.findFirstByCache(Consts.CACHE_NAMES.user.name(),"id_"+getFromUserId(),"sToelect * from s_user where id=?",getFromUserId());
	}

	public User getToUser(){
		return User.dao.findFirstByCache(Consts.CACHE_NAMES.user.name(),"id_"+getToUserId(),"select * from s_user where id=?",getToUserId());
	}

}
