package com.yhh.csap.www.model;


import com.yhh.csap.www.model.base.BasePriLetter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PriLetter extends BasePriLetter<PriLetter> {
	public static final PriLetter dao = new PriLetter().dao();

	@Override
	public String getTableName() {
		return "www_pri_letter";
	}
}
