package com.yhh.csap.www.model;


import com.yhh.csap.www.model.base.BaseReplys;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Replys extends BaseReplys<Replys> {
	public static final Replys dao = new Replys().dao();

	@Override
	public String getTableName() {
		return "www_replys";
	}
}
