package com.yhh.csap.www.model;


import com.yhh.csap.www.model.base.BaseRss;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Rss extends BaseRss<Rss> {
	public static final Rss dao = new Rss().dao();

	@Override
	public String getTableName() {
		return "www_rss";
	}
}
