package com.yhh.csap.www.model;


import com.yhh.csap.www.model.base.BaseTipoffs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tipoffs extends BaseTipoffs<Tipoffs> {
	public static final Tipoffs dao = new Tipoffs().dao();

	@Override
	public String getTableName() {
		return "www_tipoffs";
	}
}
