package com.yhh.csap.admin.model;


import com.yhh.csap.admin.model.base.BaseLogOp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogOp extends BaseLogOp<LogOp> {
	public static final LogOp dao = new LogOp().dao();
}
