package com.yhh.csap.admin.model;


import com.yhh.csap.admin.model.base.BaseMgc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mgc extends BaseMgc<Mgc> {
	public static final Mgc dao = new Mgc().dao();
}
