#namespace("doctor")
  #include("doctor.sql")
#end
#namespace("doctorVisit")
  #include("doctorVisit.sql")
#end
#namespace("userMedicalrecords")
  #include("userMedicalrecords.sql")
#end
#namespace("postInfo")
  #include("postInfo.sql")
#end
#namespace("userOps")
  #include("userOps.sql")
#end