package com.yhh.csap.www.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.yhh.csap.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFans<M extends BaseFans<M>> extends CoreModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setFanId(Integer fanId) {
		set("fanId", fanId);
	}
	
	public Integer getFanId() {
		return getInt("fanId");
	}

	public void setFollowId(Integer followId) {
		set("followId", followId);
	}
	
	public Integer getFollowId() {
		return getInt("followId");
	}

	public void setFanAt(java.util.Date fanAt) {
		set("fanAt", fanAt);
	}
	
	public java.util.Date getFanAt() {
		return get("fanAt");
	}

}
