package com.yhh.csap.www.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.yhh.csap.core.CoreModel;

import static com.jfinal.kit.PropKit.getInt;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReplys<M extends BaseReplys<M>> extends CoreModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setTargetId(Integer targetId) {
		set("targetId", targetId);
	}
	
	public Integer getTargetId() {
		return getInt("targetId");
	}

	public void setReplyId(Integer replyId) {
		set("replyId", replyId);
	}
	
	public Integer getReplyId() {
		return getInt("replyId");
	}

	public void setLikeCount(Integer likeCount) {
		set("likeCount", likeCount);
	}
	
	public Integer getLikeCount() {
		return getInt("likeCount");
	}

	public void setScore(java.math.BigDecimal score) {
		set("score", score);
	}
	
	public java.math.BigDecimal getScore() {
		return get("score");
	}

	public void setBestReply(String bestReply) {
		set("bestReply", bestReply);
	}
	
	public String getBestReply() {
		return get("bestReply");
	}

	public void setCAt(java.util.Date cAt) {
		set("cAt", cAt);
	}
	
	public java.util.Date getCAt() {
		return get("cAt");
	}

	public void setDAt(java.util.Date dAt) {
		set("dAt", dAt);
	}
	
	public java.util.Date getDAt() {
		return get("dAt");
	}

	public void setMAt(java.util.Date mAt) {
		set("mAt", mAt);
	}
	
	public java.util.Date getMAt() {
		return get("mAt");
	}

	public void setContent(String content) {
		set("content", content);
	}
	
	public String getContent() {
		return getStr("content");
	}

	public void setUserId(Integer userId) {
		set("userId", userId);
	}
	
	public Integer getUserId() {
		return getInt("userId");
	}

	public void setTargetObj(String targetObj) {
		set("targetObj", targetObj);
	}
	
	public String getTargetObj() {
		return getStr("targetObj");
	}

	public void setRootReplyId(Integer rootReplyId) {
		set("rootReplyId", rootReplyId);
	}

	public Integer getRootReplyId() {
		return getInt("rootReplyId");
	}

}
