package com.yhh.csap.www.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.yhh.csap.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNotify<M extends BaseNotify<M>> extends CoreModel<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setSender(Integer sender) {
		set("sender", sender);
	}
	
	public Integer getSender() {
		return getInt("sender");
	}

	public void setReceiver(Integer receiver) {
		set("receiver", receiver);
	}
	
	public Integer getReceiver() {
		return getInt("receiver");
	}

	public void setTxt(String txt) {
		set("txt", txt);
	}
	
	public String getTxt() {
		return getStr("txt");
	}

	public void setTitle(String title) {
		set("title", title);
	}
	
	public String getTitle() {
		return getStr("title");
	}

	public void setTargetObj(String targetObj) {
		set("targetObj", targetObj);
	}
	
	public String getTargetObj() {
		return getStr("targetObj");
	}

	public void setTargetId(Integer targetId) {
		set("targetId", targetId);
	}
	
	public Integer getTargetId() {
		return getInt("targetId");
	}

	public void setUrl(String url) {
		set("url", url);
	}
	
	public String getUrl() {
		return getStr("url");
	}

	public void setCAt(java.util.Date cAt) {
		set("cAt", cAt);
	}
	
	public java.util.Date getCAt() {
		return get("cAt");
	}

}
