package com.yhh.csap.www.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.yhh.csap.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCarouselSetting<M extends BaseCarouselSetting<M>> extends CoreModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setName(String name) {
		set("name", name);
	}
	
	public String getName() {
		return getStr("name");
	}

	public void setSummary(String summary) {
		set("summary", summary);
	}
	
	public String getSummary() {
		return getStr("summary");
	}

	public void setLinkTo(String linkTo) {
		set("linkTo", linkTo);
	}
	
	public String getLinkTo() {
		return getStr("linkTo");
	}

	public void setPic(String pic) {
		set("pic", pic);
	}
	
	public String getPic() {
		return getStr("pic");
	}

	public void setSeq(Integer seq) {
		set("seq", seq);
	}
	
	public Integer getSeq() {
		return getInt("seq");
	}

	public void setCAt(java.util.Date cAt) {
		set("cAt", cAt);
	}
	
	public java.util.Date getCAt() {
		return get("cAt");
	}

	public void setMAt(java.util.Date mAt) {
		set("mAt", mAt);
	}
	
	public java.util.Date getMAt() {
		return get("mAt");
	}

	public void setDAt(java.util.Date dAt) {
		set("dAt", dAt);
	}
	
	public java.util.Date getDAt() {
		return get("dAt");
	}

	public void setArea(String area) {
		set("area", area);
	}
	
	public String getArea() {
		return getStr("area");
	}

	public void setOperId(Integer operId) {
		set("operId", operId);
	}
	
	public Integer getOperId() {
		return getInt("operId");
	}

	public void setStatus(String status) {
		set("status", status);
	}
	
	public String getStatus() {
		return getStr("status");
	}

}
