package com.yhh.csap.www.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;
import com.yhh.csap.core.CoreModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAtMe<M extends BaseAtMe<M>> extends CoreModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setTargetId(Integer targetId) {
		set("targetId", targetId);
	}
	
	public Integer getTargetId() {
		return getInt("targetId");
	}

	public void setTargetObj(String targetObj) {
		set("targetObj", targetObj);
	}
	
	public String getTargetObj() {
		return getStr("targetObj");
	}

	public void setCAt(java.util.Date cAt) {
		set("cAt", cAt);
	}
	
	public java.util.Date getCAt() {
		return get("cAt");
	}

	public void setUserId(Integer userId) {
		set("userId", userId);
	}
	
	public Integer getUserId() {
		return getInt("userId");
	}

}
