package com.yhh.csap.core;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import com.yhh.csap.admin.model.*;
import com.yhh.csap.mt.*;
import com.yhh.csap.www.model.*;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("s_param", Param.class);
		arp.addMapping("s_res", Res.class);
		arp.addMapping("s_role", Role.class);
		arp.addMapping("s_role_res", RoleRes.class);
		arp.addMapping("s_user", User.class);
		arp.addMapping("s_user_role", UserRole.class);
		arp.addMapping("s_content", Content.class);
		arp.addMapping("s_mapping", Mapping.class);
		arp.addMapping("s_taxonomy", Taxonomy.class);
		arp.addMapping("s_attachment", Attachment.class);
		arp.addMapping("mt_doctor_info", DoctorInfo.class);
		arp.addMapping("mt_doctor_tax", DoctorTax.class);
		arp.addMapping("mt_doctor_visit", DoctorVisit.class);
		arp.addMapping("mt_doctor_visit_api", DoctorVisitApi.class);
		arp.addMapping("mt_reservation_records", ReservationRecords.class);
		arp.addMapping("mt_user_medicalrecords", UserMedicalrecords.class);
		arp.addMapping("mt_user_medicalrecords_doctor", UserMedicalrecordsDoctor.class);
		arp.addMapping("mt_user_medicalrecords_tax", UserMedicalrecordsTax.class);
		arp.addMapping("www_at_me", AtMe.class);
		arp.addMapping("www_carousel_setting", CarouselSetting.class);
		arp.addMapping("www_collect", Collect.class);
		arp.addMapping("www_fans", Fans.class);
		arp.addMapping("www_like_records", LikeRecords.class);
		arp.addMapping("www_post_info", PostInfo.class);
		arp.addMapping("www_pri_letter", PriLetter.class);
		arp.addMapping("www_replys", Replys.class);
		arp.addMapping("www_rss", Rss.class);
		arp.addMapping("www_tipoffs", Tipoffs.class);
		arp.addMapping("log_op", LogOp.class);
	}
}

